// Label offsets keep station names off their outgoing rails.
export const labels: Record<
  string,
  [number, number, "start" | "middle" | "end"]
> = {
  Vancouver: [-13, -13, "end"],
  Seattle: [-17, 4, "end"],
  Portland: [-16, 5, "end"],
  "San Francisco": [-15, -15, "middle"],
  "Los Angeles": [-24, 20, "middle"],
  Calgary: [0, -18, "middle"],
  Winnipeg: [0, -20, "middle"],
  Helena: [0, -17, "middle"],
  "Salt Lake City": [-15, -17, "end"],
  "Las Vegas": [-10, -18, "end"],
  Phoenix: [0, 24, "middle"],
  "El Paso": [0, 28, "middle"],
  "Santa Fe": [-13, 4, "end"],
  Denver: [0, -20, "middle"],
  Duluth: [-10, -15, "end"],
  Omaha: [-14, 2, "end"],
  "Kansas City": [0, 25, "middle"],
  "Oklahoma City": [38, -14, "start"],
  Dallas: [-18, 4, "end"],
  Houston: [-6, 28, "middle"],
  "Little Rock": [6, 27, "middle"],
  "New Orleans": [0, 28, "middle"],
  Chicago: [8, 38, "start"],
  "Saint Louis": [0, 27, "middle"],
  "Sault St. Marie": [0, -19, "middle"],
  Toronto: [18, 8, "start"],
  Montreal: [0, -20, "middle"],
  Boston: [18, -8, "start"],
  "New York": [17, 4, "start"],
  Pittsburgh: [0, -19, "middle"],
  Washington: [18, 6, "start"],
  Raleigh: [18, -6, "start"],
  Nashville: [-18, 0, "end"],
  Atlanta: [-14, 24, "end"],
  Charleston: [18, 7, "start"],
  Miami: [20, 8, "start"],
};
