// Label positions checked against every occupied train footprint.
export const labels: Record<
  string,
  [number, number, "start" | "middle" | "end"]
> = {
  Vancouver: [-18, -18, "middle"],
  Seattle: [-36, 0, "middle"],
  Portland: [-42, 0, "middle"],
  "San Francisco": [75, 32, "middle"],
  "Los Angeles": [-27, 28, "middle"],
  "Las Vegas": [-18, -18, "middle"],
  Phoenix: [-12, 28, "middle"],
  "El Paso": [-15, 40, "middle"],
  Calgary: [-12, -18, "middle"],
  Winnipeg: [21, -18, "middle"],
  Helena: [-60, -26, "middle"],
  "Salt Lake City": [-72, -20, "middle"],
  Denver: [18, -58, "middle"],
  "Santa Fe": [-42, -8, "middle"],
  Duluth: [6, -40, "middle"],
  Omaha: [36, 4, "middle"],
  "Kansas City": [57, -30, "middle"],
  "Oklahoma City": [-63, -48, "middle"],
  Dallas: [-24, 40, "middle"],
  Houston: [18, 28, "middle"],
  "New Orleans": [24, 28, "middle"],
  "Little Rock": [-42, -18, "middle"],
  "Saint Louis": [-60, 46, "middle"],
  Chicago: [48, 40, "middle"],
  Pittsburgh: [48, 4, "middle"],
  Nashville: [-24, -36, "middle"],
  Atlanta: [-63, 6, "middle"],
  Raleigh: [57, 18, "middle"],
  Charleston: [48, 0, "middle"],
  "New York": [66, 8, "middle"],
  Washington: [51, 0, "middle"],
  Boston: [27, -18, "middle"],
  Montreal: [0, -18, "middle"],
  "Sault St. Marie": [27, 44, "middle"],
  Toronto: [42, -4, "middle"],
  Miami: [24, -18, "middle"],
};
